### PR TITLE
fix: Support data properties

### LINKED ISSUE #71: Usage with data- attributes
I would need to use data attributes but spellcaster seems to currently not support them.

The old hyperscript project implemented these like so https://github.com/hyperhype/hyperscript/pull/5/files

### PR DESCRIPTION
**Pull request by icidasset**
Fixes #71 and #73

I wasn't sure if I needed to use the [`dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) property or `getAttribute` + `setAttribute`. I went with the latter, because the former requires you to convert all keys to camel case and I didn't want to introduce a dependency just for that.

This also allows you to use other attributes with a dash in the name such as `aria-label` (instead of using `ariaLabel`).

I also had trouble setting the `rel` attribute so included that in the `if` condition as well. Let me know if you can think of a better way of approaching this.

Tested this with computed properties as well, like so:
```ts
button(
  computed(() => ({
    className: "counter-button",
    onclick: () => setCount(count() + 1),
    "data-count": count(),
  })),
  text("Increment"),
),
```
_(let me know if I need to remove the fix for #71)_

### CODE REVIEW

File: src/spellcaster.ts [hunk 1]
```diff
@@ -86,6 +86,7 @@ const watcher = new Signal.subtle.Watcher(
     for (const signal of watcher.getPending()) {
       signal.get();
     }
+    watcher.watch();
```
Comment (gordonbrander) [inline src/spellcaster.ts:89]: Thanks for catching that 😳

**Comment by gordonbrander** [comment]
I'm nervous about the open-endedness of sniffing `-`. Can we think of any unintended consequences?

An alternative approach might be to special-case `data-`, like this:

```ts
export const setProp = (element: Element, key: string, value: any) => {
  if (LAYOUT_TRIGGERING_PROPS.has(key)) {
    console.warn(
      `Checking property value for ${key} triggers layout. Consider writing to this property without using setProp().`,
    );
  }

  if (key.startsWith("data-")) {
    element.setAttribute(key, value);
  } else if (element[key] !== value) {
    element[key] = value;
  }
};
```

However, this leaves open questions about how to handle:
- Aria properties, such as `aria-` and `role` (which has no dash)
- Listeners for custom events, which don't get nice `on` properties.

Lit handles this by making attributes the default and introducing `.prop` and `@evt` for property and event setting. However, this is less ergonomic in hyperscript. For example, this feels weird:

```ts
h('div', { ".hidden": true })
```

Some of the reasons we default to setting properties rather than attributes:

- Most DOM APIs provide mirrored properties for HTML attributes.
- The property variants have ergonomics designed for JS, and do not require string serialization/deserialization. For example, boolean attributes like `hidden` take a boolean value, and will toggle the attribute.
- This lets us do cheap comparison before setting.
- WebComponents also tend to mirror attributes and props, and in practice, tend to favor props when doing just one.

I think these advantages still hold. 

The OG hyperscript library special cases `data-` and `style`, as well as allowing for a special `attrs` key, which takes a `Record<string, any>` and sets those as attributes. 

- https://github.com/hyperhype/hyperscript/blob/master/index.js#L102C28-L102C33

Perhaps we should take that approach?

**Comment by icidasset** [comment]
> allowing for a special `attrs` key, which takes a `Record<string, any>` and sets those as attributes

Yeah, that's probably the best solution here.
I'll do something like this then?
```ts
if (key === "attrs") {
  for (const [k, v] in Object.entries(value)) {
    if (element.getAttribute(k) !== v) element.setAttribute(k, v);
  }
} else if (element[key] !== value) {
  element[key] = value;
}
```
Once we have this `attrs` value, I'm not sure we need to check for those special cases like `data-`? A clear separation between props and attributes seems like a good api.
```ts
h('div', {
  attrs: { "data-version": "v1", rel: "prev" },
  onclick: () => {},
})
```
I like it 👍

**Comment by gordonbrander** [comment]
> I'll do something like this then?
> 
> ```ts
> if (key === "attrs") {
>   for (const [k, v] in Object.entries(value)) {
>     if (element.getAttribute(k) !== v) element.setAttribute(k, v);
>   }
> } else if (element[key] !== value) {
>   element[key] = value;
> }
> ```

Yeah, exactly.

> A clear separation between props and attributes seems like a good api.

Fair point. I think it's worth considering the special-casing of `on` (registering with `addEventListener` to support custom events), but that is probably work for another PR.

Let's go with `attr` for now, and then I'm happy to land.

**Comment by icidasset** [comment]
Updated 👍 I called `toString()` on the value there because `setAttribute` requires the value to be a string (or atleast the type signature in Typescript tells me it has to be a string).

**Review by gordonbrander — APPROVED** [review]

**Comment by gordonbrander** [comment]
@icidasset this has been published to npm btw https://www.npmjs.com/package/spellcaster

**Comment by icidasset** [comment]
Thank you! 🙏
